site_name: Nikomaru Article
theme:
  name: material
  language: ja
  logo: null
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - content.code.copy
  font:
    text: Noto Sans JP
    code: JetBrains Mono
  palette:
    - scheme: default
      primary : blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary : deep orange
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
plugins:
  - blog:
      post_readtime: true
  - search:
      lang: ja
copyright: Written in 2023 by Nikomaru.  No right reserved.